### ISSUE TITLE
Duplicate repo?

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-bdi-ide#4]
What is the difference between this repo and https://github.com/big-data-europe/mu-bde-logging ?
@fr0gs

**Comment by fr0gs** [comment]
No, the **mu-bde-logging** logs http traffic for docker containers. This repository integrates the **swarm ui**, **stack builder** & **worfklow builder** systems. I am extending it to incorporate the logging by default as well, and use the **nginx-css-proxy** in order to use different css sheets and also automatic url resolution to it's correspondent container. 

I plan to create a pull request incorporating ember-engines perhaps.

**Comment by earthquakesan** [comment]
@fr0gs thanks for clarification Esteban!
